Remove customize powerlevel9k theme. Update config

diff --git a/zsh/zshrc b/zsh/zshrc
--- a/zsh/zshrc
+++ b/zsh/zshrc
@@ -1,22 +1,23 @@
-#!/bin/zsh
+#!/usr/bin/env zsh
 # ~/.zshrc
-# Last Modified: 25/01/2014 01:11 AM
 
 # Path to your oh-my-zsh configuration.
 export ZSH=$HOME/.oh-my-zsh
 
 if [[ "$COLORTERM" == "gnome-terminal" ]]; then
-    export TERM=xterm-256color
+export TERM=xterm-256color
 fi
 
 # Set name of the theme to load.
 # Look in ~/.oh-my-zsh/themes/
 # Optionally, if you set this to "random", it'll load a random theme each
 # time that oh-my-zsh is loaded
-ZSH_THEME="powerlevel9k/mrtux"
+ZSH_THEME="powerlevel9k/powerlevel9k"
 
 POWERLEVEL9K_MODE='awesome-fontconfig'
-POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon time load status root_indicator background_jobs dir vcs virtualenv rbenv)
+POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon time load status root_indicator background_jobs dir vcs aws virtualenv rbenv)
+POWERLEVEL9K_TIME_FOREGROUND='011'
+POWERLEVEL9K_TIME_BACKGROUND='$DEFAULT_COLOR'
 POWERLEVEL9K_TIME_FORMAT="%D{%H:%M:%S}"
 POWERLEVEL9K_RAM_ELEMENTS="ram_free"
 POWERLEVEL9K_STATUS_VERBOSE=false
@@ -82,15 +83,14 @@ HIST_STAMPS="dd.mm.yyyy"
 # Example format: plugins=(rails git textmate ruby lighthouse)
 # Add wisely, as too many plugins slow down shell startup.
 
-plugins=(anhoi emoi remoteoi resty adb aws autopep8 battery bower bundler capistrano
-         command-not-found copydir copyfile cp docker docker-compose fancy-ctrl-z
-         emoji emoji-clock emotty encode64 extract frontend-search git
-         git-flow git-hubflow git-extras git-remote-branch gitignore
-         golang heroku history history-substring-search httpie iwhois
-         jsontools mercurial mosh nmap perl pew pip python pylint rails rake
-         redis-cli ruby rbenv rsync sbt scala sublime screen sudo supervisor
-         systemadmin systemd tmux ubuntu urltools vagrant virtualenv
-         web-search zsh_reload z zsh-autosuggestions zsh-syntax-highlighting)
+plugins=(anhoi emoi remoteoi adb cabal command-not-found docker-compose
+         encode64 extract fancy-ctrl-z git git-extras git-flow-avh git-hubflow
+         git-remote-branch gitignore golang heroku history
+         history-substring-search httpie iwhois mercurial mosh node npm
+         nmap perl pew pip python pylint redis-cli rsync ruby gem
+         rake rbenv sbt scala stack screen sudo supervisor systemadmin
+         systemd tmux terraform ubuntu vagrant virtualenv zsh_reload ag rg z
+         zsh-autosuggestions zsh-syntax-highlighting)
 
 # User configuration
 
@@ -116,9 +116,15 @@ ZSH_TMUX_FIXTERM_WITH_256COLOR="screen-256color"
 # Google Cloud SDK
 # The next line updates PATH for the Google Cloud SDK.
 source '/home/mrtux/Applications/google-cloud-sdk/path.zsh.inc'
-
-# The next line enables bash completion for gcloud.
+# The next line enables zsh completion for gcloud.
 source '/home/mrtux/Applications/google-cloud-sdk/completion.zsh.inc'
+
+# kubectl zsh completion
+source <(kubectl completion zsh)
+# # Workaround for https://github.com/kubernetes/kubernetes/issues/27538
+# complete -o nospace -o default -F _python_argcomplete "gcloud"
+# complete -o default -F _bq_completer bq
+# complete -o nospace -F _python_argcomplete gsutil
 
 # source oh-my-zsh
 source $ZSH/oh-my-zsh.sh
@@ -169,17 +175,20 @@ setopt inc_append_history
 setopt hist_expire_dups_first
 # Do not write events to history that are duplicates of previous events
 setopt hist_ignore_dups
+setopt hist_ignore_all_dups
 # remove command line from history list when first character on the line is a space
 setopt hist_ignore_space
 # When searching history don't display results already cycled through twice
 setopt hist_find_no_dups
+# Don't write duplicate entries in the history file.
+setopt hist_save_no_dups
 # Remove extra blanks from each command line being added to history
 setopt hist_reduce_blanks
 # don't execute, just expand history
 setopt hist_verify
 # imports new commands and appends typed commands to history
 setopt share_history
-
+setopt hist_no_store
 
 # Prompt
 # Enable parameter expansion, command substitution, and arithmetic expansion in the prompt
@@ -227,6 +236,7 @@ zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
 [[ -s ~/.nix-profile/etc/profile.d/nix.sh ]] && source ~/.nix-profile/etc/profile.d/nix.sh
 
 # ssh hostname completion
+# only completion hostname in ~/.ssh/config
 zstyle -e ':completion:*:hosts' hosts 'reply=(${=${${${${(@M)${(f)"$(cat ~/.ssh/config 2>/dev/null)"}:#Host *}#Host }:#*\**}:#*\?*}})'
 
 # Automatically run ls after every cd
@@ -242,13 +252,15 @@ zstyle -e ':completion:*:hosts' hosts 'reply=(${=${${${${(@M)${(f)"$(cat ~/.ssh/
 # Using Ctrl-Space for quick execute suggest command
 bindkey '^ ' autosuggest-execute
 
-# Thefuck
-# Magnificent app which corrects your previous console command.
-eval "$(thefuck --alias)"
+# Don't store failed command to history
+zshaddhistory() { whence ${${(z)1}[1]} >| /dev/null || return 1 }
+
+# direnv
+eval "$(direnv hook zsh)"
 
 ### Keychain ###
 # Let re-use ssh-agent and/or gpg-agent between logins
-eval $(keychain --eval -Q --quiet --attempts 5 id_rsa id_ed25519 id_rsa_2048)
+eval $(keychain --eval -Q --quiet --attempts 5 id_ed25519 id_rsa id_rsa_2048)
 source $HOME/.keychain/$(hostname)-sh
 # source $HOME/.keychain/$(hostname)-sh-gpg
 
